version: "3"

volumes:
  python-consumer-log-volume:

services:
  fastapi:
    build: .
    container_name: workshop-iot-api-fastapi
    env_file: ./app/.env
    volumes:
      - ./app/:/app
      - python-consumer-log-volume:/app/logs/

  filebeat:
    image: "docker.elastic.co/beats/filebeat:8.1.1"
    container_name: workshop-iot-api-filebeat
    environment:
      - ENV=${ENV:-dev}
      - ES_ENDPOINT=${ES_ENDPOINT:-localhost:9200}
      - ES_PASSWORD=${ES_PASSWORD:-elasticpw}
    volumes:
      - ./elastic/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - python-consumer-log-volume:/logs

  nginx:
    image: nginx:1.21-alpine
    container_name: workshop-iot-api-nginx
    ports:
      - 80:80
    depends_on:
      - fastapi
    restart: always
    volumes:
      - ./nginx/fastapi.conf:/etc/nginx/conf.d/default.conf

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: workshop-iot-api-nginx-exporter
    ports:
      - 9113:9113
    command: -nginx.scrape-uri http://nginx/metrics
    depends_on:
      - nginx
